#!/usr/bin/env python3

import sys
import aoc

def main():
    if len(sys.argv) < 4:
        sys.stderr.write("Usage: %s <day> <part> <input filename>\n")
        sys.exit(-1)

    day = sys.argv[1]
    day = day.capitalize()
    part = sys.argv[2]
    filename = sys.argv[3]

    getattr(getattr(aoc, day), part)
    c = getattr(aoc, day)
    solution = c(filename)
    print(getattr(solution, part)())
    

if __name__ == "__main__":
    main()

